name: Blacklines Bot 24/7
on:
  schedule:
    - cron: '0 */4 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup System
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install python-telegram-bot groq requests Pillow
      - name: Run Engine
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          BOT_PATH=$(find . -name "bot.py" | head -n 1)
          python "$BOT_PATH"
